version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2/*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "dependencies"
    reviewers:
      - "grevian"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
