Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Resources:
  aiDiscordBotConversations:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for aiDiscordBotConversations'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-${Name}-aiDiscordBotConversations
      AttributeDefinitions:
        - AttributeName: thread_id
          AttributeType: "S"
        - AttributeName: message_unix_time
          AttributeType: "N"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: thread_id
          KeyType: HASH
        - AttributeName: message_unix_time
          KeyType: RANGE

  aiDiscordBotConversationsAccessPolicy:
    Metadata:
      'aws:copilot:description': 'An IAM ManagedPolicy for your service to access the aiDiscordBotConversations db'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: !Sub
        - Grants CRUD access to the Dynamo DB table ${Table}
        - { Table: !Ref aiDiscordBotConversations }
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DDBActions
            Effect: Allow
            Action:
              - dynamodb:BatchGet*
              - dynamodb:DescribeStream
              - dynamodb:DescribeTable
              - dynamodb:Get*
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWrite*
              - dynamodb:Create*
              - dynamodb:Delete*
              - dynamodb:Update*
              - dynamodb:PutItem
            Resource: !Sub ${ aiDiscordBotConversations.Arn}
          - Sid: DDBLSIActions
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Effect: Allow
            Resource: !Sub ${ aiDiscordBotConversations.Arn}/index/*

Outputs:
  aiDiscordBotConversationsName:
    Description: "The name of this DynamoDB."
    Value: !Ref aiDiscordBotConversations
  aiDiscordBotConversationsAccessPolicy:
    Description: "The IAM::ManagedPolicy to attach to the task role."
    Value: !Ref aiDiscordBotConversationsAccessPolicy