name: Run tests for Dependabot PRs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # Use the go version specified by the package
          go-version-file: 'go.mod'

      - name: Install Go packages
        run: |
          go mod download
      - name: Build
        run: |
          go build -o service
      - name: Run unit tests
        run: |
          go test -v ./...
