name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:  
    environment: production
    runs-on: ubuntu-latest
    concurrency: production
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200

      - uses: ksivamuthu/aws-copilot-github-action@v0.0.8
        with:
          command: deploy
          app: openai-discord-bot
          env: test # Test is prod, on this one...
          force: true
          version: v1.29.1 # Workaround for https://github.com/ksivamuthu/aws-copilot-github-action/issues/194
